# Generated by Django 2.2.7 on 2019-11-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vil_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_customer', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=2)),
                ('is_postpaid', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=2)),
                ('customer_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Customer Name')),
                ('customer_mobile_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('is_4g_sim_upgrade_pitched', models.BooleanField(default=False)),
                ('is_4g_sim_upgrade_converted', models.BooleanField(default=False)),
                ('is_voda_idea_app_pitched', models.BooleanField(default=False)),
                ('is_voda_idea_app_converted', models.BooleanField(default=False)),
                ('is_non_telco_offer_edu_pitched', models.BooleanField(default=False)),
                ('is_non_telco_offer_edu_converted', models.BooleanField(default=False)),
                ('is_plan_upgrading_to_unlimited_pitched', models.BooleanField(default=False)),
                ('is_plan_upgrading_to_unlimited_converted', models.BooleanField(default=False)),
                ('is_email_updation_pitched', models.BooleanField(default=False)),
                ('is_email_updation_converted', models.BooleanField(default=False)),
                ('is_non_mobility_pitched', models.BooleanField(default=False)),
                ('is_non_mobility_converted', models.BooleanField(default=False)),
                ('is_reference_add_on_pitched', models.BooleanField(default=False)),
                ('is_reference_add_on_converted', models.BooleanField(default=False)),
                ('insertion_date_time', models.DateTimeField(auto_now_add=True)),
                ('updation_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
