# Generated by Django 2.2.7 on 2019-11-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vil_panel', '0002_storedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedetail',
            name='insertion_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storedetail',
            name='updation_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
