# Generated by Django 2.2.7 on 2019-11-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vil_panel', '0003_auto_20191128_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedetail',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile'),
        ),
    ]
