# Generated by Django 2.2.7 on 2019-12-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vil_panel', '0004_storedetail_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedetail',
            name='insertion_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='storedetail',
            name='updation_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated on'),
        ),
    ]
