# Generated by Django 2.2.7 on 2019-11-28 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('ST', 'Store'), ('SM', 'Store Manager'), ('CL', 'Circle'), ('ZN', 'Zone')], max_length=2)),
                ('store_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Store Name')),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('zone_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Zone Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
